### ISSUE TITLE
Repository state

### ISSUE THREAD

**Issue by gsaadeh** [telerik/kendo-angular-component-base#5]
I see that the repository has been updated to RC. Are we supposed to still use the existing hack to integrate Kendo with Angular2 or should we wait for this to mature?

**Comment by ggkrustev** [comment]
I would suggest you check this blog post that sheds more light on the topic:
- http://www.telerik.com/blogs/kendo-ui-for-angular-2-r3-roadmap

I will close this thread for now, as it is not related to any bug report or feature.
